### ISSUE TITLE
update Info.plist for iOS 8

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-me#7]
Per https://github.com/mapbox/mapbox-ios-sdk/issues/481 & https://github.com/mapbox/mapbox-ios-sdk/commit/8d6b14a9a8463a80b6aff96a2d22df0648d41ca0 this app is going to need a `NSLocationWhenInUseUsageDescription` value in its `Info.plist` once we update the SDK to one built against iOS 8.

**Comment by friedbunny** [comment]
Fixed by 109e362b74f43adc121ea7d9697f09caa8d7146b.
